version: '2'
services:
  db:
    image: postgres
  web:
    build:
      dockerfile: containers/web/Dockerfile
      context: .
      args:
        HTTP_PROXY: ${HTTP_PROXY}
    links:
    - db
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
    - .:/myapp
    ports:
    - "3000:3000"
    depends_on:
    - db
    env_file:
    - '.env.web'
